### ISSUE TITLE
Frequent connection errors

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/vigilant-crypto-snatch#23]
There are many connection errors, likely from me suspending my laptop. It is getting on my nerves. I finally have a full traceback:

```
2022-01-07 07:35:08 mu-x220 vigilant_crypto_snatch[97922] DEBUG Checking trigger “Large drops” …
2022-01-07 07:35:08 mu-x220 vigilant_crypto_snatch[97922] DEBUG Could not find entry in the database.
2022-01-07 07:35:08 mu-x220 vigilant_crypto_snatch[97922] DEBUG <vigilant_crypto_snatch.historical.concrete.MarketSource object at 0x7f4ea1e00760>
2022-01-07 07:51:14 mu-x220 vigilant_crypto_snatch[97922] WARNING An exception of type <class 'vigilant_crypto_snatch.myrequests.HttpRequestError'> has occurred: Connection error in Kraken Ticker
2022-01-07 07:51:14 mu-x220 urllib3.connectionpool[97922] DEBUG Starting new HTTPS connection (1): api.telegram.org:443
2022-01-07 07:51:14 mu-x220 vigilant_crypto_snatch[97922] DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib64/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.10/site-packages/urllib3/packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib64/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mu/.local/lib/python3.10/site-packages/vigilant_crypto_snatch/marketplace/krakenex_adaptor.py", line 58, in get_spot_price
    answer = self.handle.query_public(
  File "/home/mu/.local/lib/python3.10/site-packages/krakenex/api.py", line 162, in query_public
    return self._query(urlpath, data, timeout = timeout)
  File "/home/mu/.local/lib/python3.10/site-packages/krakenex/api.py", line 134, in _query
    self.response = self.session.post(url, data = data, headers = headers,
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mu/.local/lib/python3.10/site-packages/vigilant_crypto_snatch/watchloop.py", line 53, in process_trigger
    if trigger.has_cooled_off(now) and trigger.is_triggered(now):
  File "/home/mu/.local/lib/python3.10/site-packages/vigilant_crypto_snatch/triggers/concrete.py", line 73, in is_triggered
    return all(
  File "/home/mu/.local/lib/python3.10/site-packages/vigilant_crypto_snatch/triggers/concrete.py", line 74, in <genexpr>
    triggered_delegate.is_triggered(now)
  File "/home/mu/.local/lib/python3.10/site-packages/vigilant_crypto_snatch/triggers/triggered_delegates.py", line 30, in is_triggered
    price = self.source.get_price(now, self.coin, self.fiat)
  File "/home/mu/.local/lib/python3.10/site-packages/vigilant_crypto_snatch/historical/concrete.py", line 110, in get_price
    price = live_source.get_price(then, coin, fiat)
  File "/home/mu/.local/lib/python3.10/site-packages/vigilant_crypto_snatch/historical/concrete.py", line 78, in get_price
    price = self.market.get_spot_price(coin, fiat, then)
  File "/home/mu/.local/lib/python3.10/site-packages/vigilant_crypto_snatch/marketplace/krakenex_adaptor.py", line 62, in get_spot_price
    raise HttpRequestError("Connection error in Kraken Ticker") from e
vigilant_crypto_snatch.myrequests.HttpRequestError: Connection error in Kraken Ticker
```

I'll have to look into that further and maybe just ignore those errors.

**Comment by martin-ueding** [comment]
I just log these as debug errors, and then they don't show up in Telegram any more.
