### ISSUE TITLE
Telegram messages too long

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/vigilant-crypto-snatch#8]
Some Telegram messages are just too long, and then they crash.

```
2021-06-11 16:22:23 mu-x220 vigilant_crypto_snatch[1248759] DEBUG Sending message to Telegram …
2021-06-11 16:22:23 mu-x220 urllib3.connectionpool[1248759] DEBUG Starting new HTTPS connection (1): api.telegram.org:443
2021-06-11 16:22:23 mu-x220 urllib3.connectionpool[1248759] DEBUG https://api.telegram.org:443 "POST /bot1694484080:AAEj-nsXdZbuv1mx3utFBKsNLDcURfKCIzU/sendMessage HTTP/1.1" 400 78
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib64/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 353, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.kraken.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/watchloop.py", line 60, in process_trigger
    if trigger.has_cooled_off(now) and trigger.is_triggered(now):
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/triggers.py", line 143, in is_triggered
    return self.triggered_delegate.is_triggered(now)
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/triggers.py", line 37, in is_triggered
    price = self.source.get_price(now, self.coin, self.fiat)
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/historical.py", line 142, in get_price
    price = live_source.get_price(then, coin, fiat)
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/historical.py", line 110, in get_price
    price = self.market.get_spot_price(coin, fiat, then)
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/marketplace/krakenex_adaptor.py", line 46, in get_spot_price
    answer = self.handle.query_public(
  File "/home/mu/.local/lib/python3.9/site-packages/krakenex/api.py", line 162, in query_public
    return self._query(urlpath, data, timeout = timeout)
  File "/home/mu/.local/lib/python3.9/site-packages/krakenex/api.py", line 134, in _query
    self.response = self.session.post(url, data = data, headers = headers,
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.kraken.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mu/.local/bin/vigilant-crypto-snatch", line 8, in <module>
    sys.exit(main())
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/cli.py", line 57, in main
    options.func(options)
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/cli.py", line 63, in main_watch
    watchloop.main(options)
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/watchloop.py", line 121, in main
    trigger_loop.loop()
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/watchloop.py", line 37, in loop
    self.loop_body()
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/watchloop.py", line 45, in loop_body
    process_trigger(trigger, self.keepalive)
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/watchloop.py", line 77, in process_trigger
    logger.critical(
  File "/usr/lib64/python3.9/logging/__init__.py", line 1493, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/telegram.py", line 57, in emit
    self.send_message(self.format(record))
  File "/home/mu/.local/lib/python3.9/site-packages/vigilant_crypto_snatch/telegram.py", line 46, in send_message
    raise TelegramBotException(
vigilant_crypto_snatch.telegram.TelegramBotException: Error sending to telegram. Response: `{"ok": false, "error_code": 400, "description": "Bad Request: message is too long"}`
```

**Comment by martin-ueding** [comment]
The maximum length is 4096 UTF-8 characters, according to https://limits.tginfo.me/de-DE. This is then easy to fix. We can just split by lines and take as many until we have the length. We just split then. If there are single lines that are too long, we need to split those.

**Comment by martin-ueding** [comment]
Telegram messages are now chunked such that they don't exceed the limits
